export default [
  {
    id: "1",
    title: "Book 1",
    author: "Author 1",
    image: "https://imgur.com/t/books/EpMpSzx",
    price: 20.99,
  },
  {
    id: "2",
    title: "Book 2",
    author: "Author 2",
    image: "https://imgur.com/t/books/EpMpSzx",
    price: 15.5,
  },
  {
    id: "3",
    title: "Book 3",
    author: "Author 3",
    image: "https://imgur.com/t/books/EpMpSzx",
    price: 25.99,
  },
  {
    id: "4",
    title: "Book 4",
    author: "Author 4",
    image: "https://imgur.com/t/books/EpMpSzx",
    price: 18.99,
  },
  {
    id: "5",
    title: "Book 5",
    author: "Author 5",
    image: "https://imgur.com/t/books/EpMpSzx",
    price: 30.99,
  },
  {
    id: "6",
    title: "Book 6",
    author: "Author 6",
    image: "https://imgur.com/t/books/EpMpSzx",
    price: 22.5,
  },
  {
    id: "7",
    title: "Book 7",
    author: "Author 7",
    image: "https://imgur.com/t/books/EpMpSzx",
    price: 19.99,
  },
  {
    id: "8",
    title: "Book 8",
    author: "Author 8",
    image: "https://imgur.com/t/books/EpMpSzx",
    price: 17.99,
  },
  {
    id: "9",
    title: "Book 9",
    author: "Author 9",
    image: "https://imgur.com/t/books/EpMpSzx",
    price: 24.99,
  },
  {
    id: "10",
    title: "Book 10",
    author: "Author 10",
    image: "https://imgur.com/t/books/EpMpSzx",
    price: 21.99,
  },
  {
    id: "11",
    title: "Book 11",
    author: "Author 11",
    image: "https://imgur.com/t/books/EpMpSzx",
    price: 27.99,
  },
  {
    id: "12",
    title: "Book 12",
    author: "Author 12",
    image: "https://imgur.com/t/books/EpMpSzx",
    price: 29.99,
  },
  {
    id: "13",
    title: "Book 13",
    author: "Author 13",
    image: "https://imgur.com/t/books/EpMpSzx",
    price: 20.5,
  },
  {
    id: "14",
    title: "Book 14",
    author: "Author 14",
    image: "https://imgur.com/t/books/EpMpSzx",
    price: 25.5,
  },
  {
    id: "15",
    title: "Book 15",
    author: "Author 15",
    image: "https://imgur.com/t/books/EpMpSzx",
    price: 22.99,
  },
  {
    id: "16",
    title: "Book 16",
    author: "Author 16",
    image: "https://imgur.com/t/books/EpMpSzx",
    price: 26.99,
  },
  {
    id: "17",
    title: "Book 17",
    author: "Author 17",
    image: "https://imgur.com/t/books/EpMpSzx",
    price: 28.5,
  },
  {
    id: "18",
    title: "Book 18",
    author: "Author 18",
    image: "https://imgur.com/t/books/EpMpSzx",
    price: 24.5,
  },
  {
    id: "19",
    title: "Book 19",
    author: "Author 19",
    image: "https://imgur.com/t/books/EpMpSzx",
    price: 21.5,
  },
  {
    id: "20",
    title: "Book 20",
    author: "Author 20",
    image: "https://imgur.com/t/books/EpMpSzx",
    price: 19.5,
  },
];
